set_property PACKAGE_PIN M17 [get_ports a]
set_property PACKAGE_PIN L16 [get_ports b]
set_property PACKAGE_PIN J15 [get_ports y]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports y]
